version: '3.2'
services:
  frontend:
    image: ${SQUASH_REGISTRY}:django-react-todo-front-default-{SQUASH_MATCH_BRANCH}
    ports:
      - 80:3000

  backend:
    build: ./
    command: bash ./run_server.sh
    ports:
      - 8000:8000
